[build]
  publish = "_site"
  command = "npm run build-production"

[[plugins]]
package = "./plugins/keep-data-cache"

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://speedlify.netlify.app"
  to = "https://www.speedlify.dev"
  status = 301
  force = true

[context.branch-deploy.environment]
  PUPPETEER_CACHE_DIR = "/opt/build/repo/node_modules/.cache/puppeteer-bin/"

[context.deploy-preview.environment]
  PUPPETEER_CACHE_DIR = "/opt/build/repo/node_modules/.cache/puppeteer-bin/"

[context.production.environment]
  PUPPETEER_CACHE_DIR = "/opt/build/repo/node_modules/.cache/puppeteer-bin/"
  PENDO_KEY = "87c9b7d6-be41-4b7f-5cde-3f452463a714"
